### ISSUE TITLE
Is there a plan to remove airflow.readthedocs.io ?

### ISSUE THREAD

**Issue by louisguitton** [apache/airflow-site#251]
I was googling around to find some docs and here is the order of search results I got: 
![image](https://user-images.githubusercontent.com/7823843/74609294-1d748900-50e9-11ea-827b-d56263b49f40.png)

https://airflow.readthedocs.io/ in this case came before https://airflow.apache.org/ . 
Is this the intended behaviour ? 
As a user, I'd prefer browsing all the time the same website.

**Comment by mik-laj** [comment]
airflow.readthedocs.org provides us with documentation from the master branch. 
This is very problematic to configure on Apache servers because uploading changes to the site is done via git. Changes in Git can only be made by the Jenkins bot or commiters. We don't use Jenkins, so configuring it to update documentation would be problematic.  We are thinking of another solution that will comply with the Apache rules e.g. the rules regarding the use of Github Action in Apache have changed recently and I hope that we will soon be able to develop a solution that will allow us to configure CI/CD, but it takes time to discuss with the Infra team.

Related PR: https://github.com/apache/airflow-site/issues/226

**Comment by mik-laj** [comment]
I close because I answered the question. In addition, this task has a large dependence on other tasks, so we will not be able to do anything with it in the near future.

**Comment by louisguitton** [comment]
thanks for your answer

**Comment by mik-laj** [comment]
We dropped support for RTD. The documentation for the master is published at https://s.apache.org/airflow-docs
