### ISSUE TITLE
Cannot select Airflow version on CLI and Macros Documentation

### ISSUE THREAD

**Issue by wolfier** [apache/airflow-site#361]
**Apache Airflow version**: N/A

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): N/A

**Environment**:

- **Chrome Version**: Version 87.0.4280.88 (Official Build) (x86_64)
-  **Safari Version**: Version 14.0 (15610.1.28.1.9, 15610)

**What happened**:

I was unable to select the version for the documentation page on CLI and Macros

**What you expected to happen**:

I expect to be able to select the version and for there to be no errors on the console.

**How to reproduce it**:

Go to the [Macros](https://airflow.apache.org/docs/apache-airflow/stable/macros-ref.html
) or [CLI](https://airflow.apache.org/docs/apache-airflow/stable/macros-ref.html) reference documentation.

Check chrome console.

CLI
```
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#Positional%20Arguments' is not a valid selector.
```
![Screen Shot 2020-12-18 at 3 25 41 PM](https://user-images.githubusercontent.com/5952735/102672335-56382100-4145-11eb-9b03-7dcdc69f96a3.png)

Macros
```
Uncaught TypeError: Cannot read property 'offsetTop' of null
```
![Screen Shot 2020-12-18 at 3 25 34 PM](https://user-images.githubusercontent.com/5952735/102672339-589a7b00-4145-11eb-99bc-d81245a91c9d.png)

**Comment by ashb** [comment]
Thanks Alan -- have moved this in to the 'airflow-site' repo.

**Comment by mik-laj** [comment]
I confirm. I have this problem too. This issue appears to have been reported previously. See: https://github.com/apache/airflow-site/issues/254

I took a quick look at it and it seems to me it is enough to make the following change to this problem, but I don't have time to check it and update all the files on docs-archive.
https://github.com/apache/airflow-site/blob/11f9122db84d89ea0508ec8e3516e328c4df4158/landing-pages/src/js/progressTracking.js#L34
```diff
-      targetElement = document.querySelector(`#${target}`);
+      targetElement = document.getElementById(target);
```
When an element has an ID that contains a dot symbol, the expression parser gets lost and cannot find the element because it starts interpreting part of the expression as [a class selector](https://developer.mozilla.org/pl/docs/Web/CSS/Selektor_klasy).
@wolfier Can you see if this fixes this problem?
