### ISSUE TITLE
Announcements page does not have links to source releases

### ISSUE THREAD

**Issue by sebbASF** [apache/airflow-site#505]
The page https://airflow.apache.org/announcements/ should contain links to the sources

**Comment by potiuk** [comment]
Good point ! Thanks @sebbASF. PR on the way.

**Comment by kaxil** [comment]
Thanks @sebbASF

**Comment by potiuk** [comment]
It's already live (Shift + refresh) if you have it cached.

**Comment by sebbASF** [comment]
Thanks, but what about 2.1.3 and earlier source links?

**Comment by potiuk** [comment]
We don't have them. We are supposed to only support the download links for all the "active" branches arent' we? We only support 2.1 an 2.2 branches now.

**Comment by sebbASF** [comment]
What about:
https://airflow.apache.org/docs/apache-airflow/2.1.3/installation.html#installing-airflow-from-released-sources-and-packages
and
https://airflow.apache.org/docs/apache-airflow/2.1.0/installation.html#installing-airflow-from-released-sources-and-packages

**Comment by kaxil** [comment]
@sebbASF @potiuk  - https://github.com/apache/airflow-site/pull/507

**Comment by potiuk** [comment]
> What about: https://airflow.apache.org/docs/apache-airflow/2.1.3/installation.html#installing-airflow-from-released-sources-and-packages and https://airflow.apache.org/docs/apache-airflow/2.1.0/installation.html#installing-airflow-from-released-sources-and-packages

Ah yeah we could add those easily. I was following the general approach that from each "active" line we should really keep the latest and all the rest is "archived" and we should really promote the "latest" versions to be installed. 

Since we did not have those pages further in the past (but released are ok in archives)  going even farther in the past was neither flagged as a problem, nor is required by any policies, I believe. We want our users to install latest versions only as they contain latest security and bug fixes, so updating old announcements makes little sense.

**Comment by sebbASF** [comment]
My take is that if you provide a link to the binaries for a particular version, you must also link to the source.
The ASF releases source code.

**Comment by potiuk** [comment]
I think it's best to ask on the users@infra. Could you please ask for clarification there, since it's your doubt?

**Comment by sebbASF** [comment]
What makes you think that it is OK to link to binaries and not provide a link to the source that was used to create the binary?

**Comment by potiuk** [comment]
I don't think it's OK. I just think that if we did it wrongly in the past
and fixed it in recent releases after we were made aware of it - we do not
have to retroactively fix it. We did it wrong. This is clear. Do we have to
fix it in the past - I don't think so - but if you think otherwise - feel
free to start a thread about it and ask. I feel no need to ask but if you
do - it's all yours.

J.
